services:
  - type: web
    name: beeblog
    env: static
    buildCommand: pnpm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: redirect
        from: /feed
        to: /feed.xml
      - type: redirect
        from: /rss
        to: /feed.xml
      - type: redirect
        from: /rss.xml
        to: /feed.xml
