name: E2E
on: [deployment_status]
jobs:
  accessibility:
    if: github.event.deployment_status.state == 'success'
    # WORKAROUND: https://github.com/pa11y/pa11y/issues/651
    runs-on: ubuntu-latest
    permissions:
      checks: read
      pull-requests: write
    steps:
      - uses: narthur/pa11y-ratchet@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          sitemap-url: ${{github.event.deployment_status.target_url}}/sitemap-0.xml
          find: https://blog.beeminder.com
          replace: ${{github.event.deployment_status.target_url}}
          include: 'https?:\/\/[\w\.-]+\/en\/'